// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwshuyuhmmmvfnsmrogz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3c2h1eXVobW1tdmZuc21yb2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODEyNzAsImV4cCI6MjA2MDg1NzI3MH0.Q7Zw8182Up_QTwVQJkz9OTiZJMKTJ9MY1JJqOZGxs94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);